### ISSUE TITLE
Crash after  derealistiation

### ISSUE THREAD

**Issue by 2uller2** [VitaliiAndreev/WarThunder_PresetRandomizer#12]
Hello, i have a crash error. erm is there any way to fix??

**Comment by VitaliiAndreev** [comment]
Oi oi. The issue has been fixed in [0.3.2.3](https://github.com/VitaliiAndreev/WarThunder_PresetRandomizer/releases/tag/0.3.2.3). The latest release is [0.3.2.4](https://github.com/VitaliiAndreev/WarThunder_PresetRandomizer/releases/tag/0.3.2.4) though ("Ixwa Strike" came out shortly after 0.3.2.3). C:
